import { type NextPage } from "next";
import Head from "next/head";
import { FormGroup } from "~/component/FormGroup";
import { Input } from "~/component/Input";
import { api } from "~/utils/api";

const GeneratePage: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form className="flex flex-col gap-4">
          <FormGroup>
          <label>Prompt</label>
          <Input></Input>
          </FormGroup>
          <button className="rounded bg-blue-400 hover:bg-blue-500 px-4 py-2">Submit</button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
